ktor:
    application:
        modules:
            - com.ajuliaoo.ibtlibrary.ApplicationKt.module
    deployment:
        port: 8080
    database:
        url: $DATABASE_URL
        user: $DATABASE_USER
        password: $DATABASE_PASSWORD
